iCalWebApp/Controllers/EventsListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Core.Events;
using Core.Interfaces;
using iCalWebApp.Models;
using Event = DDay.iCal.Event;
using System.IO;
using iCalWebApp.Extensions;
using System.Collections.ObjectModel;
using DDay.iCal;

namespace iCalWebApp.Controllers
{
	public class EventsListController : Controller
	{
		//public List<Event> Events = new List<Event>();
		// GET: EventsList
		public ActionResult Index()
		{
			ViewBag.Upload = false;
			return View(FetchEvents());
		}

		/// <summary>
		/// Dodaje nowy obiekt Event do listy zdefiniowanych eventów
		/// </summary>
		/// <param name="model">obiekt modelu do dodania</param>
		private void AddEvent(EventModel model)
		{
			EventCollection events = FetchEvents();

			events.Add(model);
		}

		/// <summary>
		/// Pobiera zapisaną w sesji listę obiektów Event
		/// </summary>
		/// <returns>Zwraca listę Event</returns>
		private EventCollection FetchEvents()
		{
			if (Session["Events"] == null)
			{
				Session["Events"] = new EventCollection();
				return FetchEvents();
			}

			return (EventCollection) Session["Events"];

		}
	  
		// GET: EventsList/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: EventsList/Create
		[HttpPost]
		public ActionResult Create(EventModel model)
		{
			try
			{
				if (ModelState.IsValid)
				{
					/*if (model.SelectedFrequency.Any())
					{
						model.Recurrence = model.SelectedFrequency;
					}*/
					AddEvent(model);
				}

				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}

		// GET: EventsList/Edit/5
		public ActionResult Edit(string id)
		{
			EventModel model = FetchEvents().Get(id);
			return View(model);
		}

		// POST: EventsList/Edit/5
		[HttpPost]
		public ActionResult Edit(EventModel model, FormCollection collection)
		{
			try
			{
				//Event old = FetchEvents().Get(id);
				//model.Guid = old.Guid;
				if (ModelState.IsValid)
				{
					AddEvent(model);
				}

				return RedirectToAction("Index");
				
			}
			catch
			{
				return View();
			}
		}

		/// <summary>
		/// Usuwa podany event z listy eventów na stronie
		/// </summary>
		/// <param name="id">guid modelu do usunięcia</param>
		/// <returns></returns>
		// GET: EventsList/Delete/5
		public ActionResult Delete(string id)
		{
			return View(FetchEvents().Get(id));
		}

		// POST: EventsList/Delete/5
		[HttpPost]
		public ActionResult Delete(string id, FormCollection collection)
		{
			try
			{
				FetchEvents().Remove(id);

				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}

		public ActionResult DeleteAll()
		{
			return View(FetchEvents());
		}

        public ActionResult DownloadCalendar()
        {
            Parser iCalParser = new Parser();
            string filePath = Server.MapPath(string.Format(@"~\files\{0}.ics", Guid.NewGuid())); // this is file path

			foreach (EventModel @event in FetchEvents())
	        {
		        iCalParser.calendar.Events.Add(@event);
	        }

			using (StreamWriter outputFile = new StreamWriter(filePath))
            {
                outputFile.Write(iCalParser.ParseToString());
            }

            Response.ContentType = "text/calendar";
            Response.AppendHeader("content-disposition",
                    "attachment; filename=" + Path.GetFileName(filePath));
            Response.TransmitFile(filePath);
            Response.End();
	        return null;

        }

        private void UploadCalendar(string filePath)
        {
            Parser iCalParser = new Parser();
            ICollection<IEvent> events = iCalParser.ParseToCalendar(filePath).Events;
            Session["Events"] = new EventCollection(events);
        }

        [HttpPost]
		public ActionResult DeleteAll(FormCollection collection)
		{
			try
			{
				FetchEvents().Clear();

				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}

		//[HttpPost]
		//public ActionResult UploadCalendar()
		//{
		//	//teamName is a string passed from a session object upon login 
		//	string filePath = "SFiles/Submissions/" + teamName + "/";
		//	string severFilePath = Server.MapPath(filePath);
		//	//If directory does not exist
		//	if (!Directory.Exists(severFilePath))
		//	{ // if it doesn't exist, create

		//		System.IO.Directory.CreateDirectory(severFilePath);
		//	}

		//	f_sourceCode.SaveAs(severFilePath + src));
		//	f_poster.SaveAs(severFilePath + bb));
		//}






		[HttpPost]
		public ActionResult UploadCalendar()
		{
			var upload = Request.Files[0];
			if (upload.HasFile())
			{
				string path = Server.MapPath("/");
				string filename = Path.GetFileName(upload.FileName);
				path = Path.Combine(path, filename);
				upload.SaveAs(path);
				UploadCalendar(path);
			}
			return RedirectToAction("Index");
		}

		public ActionResult VievUploadModal()
		{
			ViewBag.Upload = true;
			return View("Index", FetchEvents());
		}

	}
}

iCalWebApp/Views/EventsList/Create.cshtml
@model Core.Events.EventModel

@{
	ViewBag.Title = "CreateView";
	Layout = "../Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="../../Content/bootstrap-iso.css" />
<link rel="stylesheet" href="../../Content/bootstrap-datetimepicker.css" />
<link rel="stylesheet" href="../../Content/font-awesome.min.css" />

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>Event</h4>
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
	    <div class="list-group-item">
	        <div class="form-group">
	            @Html.LabelFor(model => model.Summary, htmlAttributes: new {@class = "control-label col-md-2"})
	            <div class="col-md-10">
	                <div class="input-group">
	                    <div class="input-group-addon">
	                        <i class="fa fa-commenting-o">
	                        </i>
	                    </div>
	                    @Html.EditorFor(model => model.Summary, new {htmlAttributes = new {@class = "form-control"}})
	                    @Html.ValidationMessageFor(model => model.Summary, "", new {@class = "text-danger"})
	                </div>
	            </div>
	        </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar-o">
                            </i>
                        </div>
                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                    </div>
                </div>
            </div>
	    </div>

	    <div class="dateRangePicker">
			<div class="list-group-item">
				<div class="form-group">
					@Html.LabelFor(model => model.From, "Start date", htmlAttributes: new { @class = "control-label col-md-2", @for = "dateFrom" })
					<div class="col-md-10">
						<div class="input-group">
							<div class="input-group-addon">
								<i class="fa fa-calendar-plus-o">
								</i>
							</div>
							@Html.EditorFor(model => model.From, new { htmlAttributes = new { @class = "form-control", @id = "dateFrom", @placeholder = "MM/DD/YYYY", @type = "text" } })
							@Html.ValidationMessageFor(model => model.From, "", new { @class = "text-danger" })
						</div>
					</div>
				</div>

				<div class="form-group">
					@Html.LabelFor(model => model.Start.TimeZoneName, "Timezone", htmlAttributes: new { @class = "control-label col-md-2", @for = "dateFrom.TimeZoneName" })
					<div class="col-md-10">
						<div class="input-group">
							<div class="input-group-addon">
								<i class="fa fa-calendar-plus-o">
								</i>
							</div>
							@Html.DropDownListFor(model => model.Start.TimeZoneName,
											new SelectList(new string[] { }),
											htmlAttributes: new { @class = "form-control", @id = "timezone-select-from", @type = "text" })

							@Html.ValidationMessageFor(model => model.Start.TimeZoneName, "", new { @class = "text-danger" })
						</div>
					</div>
				</div>
			</div>

			<div class="list-group-item">
				<div class="form-group">
					@Html.LabelFor(model => model.To, "End date", htmlAttributes: new { @class = "control-label col-md-2", @for = "dateTo" })
					<div class="col-md-10">
						<div class="input-group">
							<div class="input-group-addon">
								<i class="fa fa-calendar-plus-o">
								</i>
							</div>
							@Html.EditorFor(model => model.To, new { htmlAttributes = new { @class = "form-control", @id = "dateTo", @placeholder = "MM/DD/YYYY", @type = "text" } })
							@Html.ValidationMessageFor(model => model.To, "", new { @class = "text-danger" })
						</div>
					</div>
				</div>

				<div class="form-group">
					@Html.LabelFor(model => model.End.TimeZoneName, "Timezone", htmlAttributes: new { @class = "control-label col-md-2", @for = "dateTo.TimeZoneName" })
					<div class="col-md-10">
						<div class="input-group">
							<div class="input-group-addon">
								<i class="fa fa-calendar-plus-o">
								</i>
							</div>
							@Html.DropDownListFor(model => model.End.TimeZoneName,
												new SelectList(new string[] { }),
												htmlAttributes: new { @class = "form-control", @id = "timezone-select-to", @type = "text" })

							@Html.ValidationMessageFor(model => model.End.TimeZoneName, "", new { @class = "text-danger" })
						</div>
					</div>
				</div>
			</div>

			<div class="list-group-item">
				<div class="form-group">
					@Html.LabelFor(model => model.IsAllDay, "All day event", htmlAttributes: new { @class = "control-label col-md-2" })
					<div class="col-md-1">
     
                        @Html.CheckBoxFor(model => model.IsAllDay, htmlAttributes: new { @checked = "checked", @class = "checkbox" })
					</div>
				</div>

				<div class="form-group">
					@Html.LabelFor(model => model.AlarmObj.Description, "Description", htmlAttributes : new { @class = "control-label col-md-2" })
					<div class="col-md-10">
						<div class="input-group">
							<div class="input-group-addon">
								<i class="fa fa-calendar-o">
								</i>
							</div>
							@Html.TextAreaFor(model => model.AlarmObj.Description, new { @class = "form-control" })
						</div>
					</div>
				</div>

				<div class="form-group">
					@Html.LabelFor(model => model.DurationObj, "Reminder time", htmlAttributes : new { @class = "control-label col-md-2", @for = "alarm" })
					<div class="col-md-10">
						<div class="input-group">
							<div class="input-group-addon">
								<i class="fa fa-calendar-o">
								</i>
							</div>
							@Html.EditorFor(model => model.DurationObj, new { htmlAttributes = new { @class = "form-control", @id = "alarm", @type = "text" } })
						</div>
					</div>
				</div>

				@*<div class="form-group">
					@Html.LabelFor(model => model.RecurrenceRules, "Repeat", htmlAttributes: new { @class = "control-label col-md-2" })

					
						<div class="col-md-10">
							<div class="input-group">
								<div class="input-group-addon">
									<i class="fa fa-calendar-o">
									</i>
								</div>
								@Html.CheckBoxListFor(model => model.AvailableFrequency, model => model.AvailableFrequency, model => model.SelectedFrequency, Position.Vertical)
							</div>
						</div>
					
					
				</div>*@
			</div>
		</div>

		<div class="form-group">
            <p> </p>
            <div class="col-md-offset-8 col-md-10">
                <input type="button" value="Back" class="button" onclick="location.href='@Url.Action("Index")'" />
                <input type="submit" value="Create" class="button" />
            </div>
		</div>
	</div>

}

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script type="text/javascript" src="~/scripts/moment-with-locales.min.js"></script>
<script type="text/javascript" src="~/scripts/bootstrap-datetimepicker.js"></script>
<script type="text/javascript" src="~/scripts/select2.js"></script>
<script type="text/javascript" src="~/scripts/timeZoneSelect.js"></script>
<script type="text/javascript" src="~/scripts/dateObject.js"></script>

iCalWebApp/Views/EventsList/Delete.cshtml
@model Core.Events.EventModel

@{
	ViewBag.Title = "Delete";
	Layout = "../Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
           Title
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Summary)
        </dd>

        <dt>
            Commentary
        </dt>

	    <dd>
		    @Html.DisplayFor(model => model.Description)
	    </dd>

		<dt>
			From
		</dt>

	    <dd>
		    @Html.DisplayFor(model => model.From)
	    </dd>

		<dt>
			To
		</dt>

		<dd>
			@Html.DisplayFor(model => model.To)
		</dd>

	    <dt>
            Created
        </dt>

	    <dd>
		    @Html.DisplayFor(model => model.Created)
	    </dd>

		<dt>
			Is all day event
		</dt>

		<dd>
			@Html.DisplayFor(model => model.IsAllDay)
		</dd>

	    @Html.HiddenFor(model => model.UID)

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

     
        <div class= "col-md-offset-0 col-md-10">
            <input type ="button" value="Back" class="button" onclick="location.href='@Url.Action("Index")'" />
            <input type="submit" value="Delete" class="button"/>
            <p></p>
        </div>
    }
</div>

iCalWebApp/Views/EventsList/DeleteAll.cshtml
@model IEnumerable<Core.Events.EventModel>

@{
	ViewBag.Title = "Deleting All Elements";
	Layout = "../Shared/_Layout.cshtml";
}

<h2>Delete all</h2>

<h3>Are you sure you want to delete all @Model.Count() events?</h3

<p></p>

@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()


	<div class="col-md-offset-0 col-md-10">
		<input type ="button" value="Back" class="button" onclick="location.href='@Url.Action("Index")'" />
	    <input type="submit" value="Delete all" class="button"/>
        <p></p>
	</div>
}

iCalWebApp/Views/EventsList/Edit.cshtml
@model Core.Events.EventModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="../../Content/bootstrap-iso.css" />
<link rel="stylesheet" href="../../Content/bootstrap-datetimepicker.css" />
<link rel="stylesheet" href="../../Content/font-awesome.min.css"/>

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Event</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="list-group-item">
            <div class="form-group">

                @Html.LabelFor(model => model.Summary, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-commenting-o">
                            </i>
                        </div>
                        @Html.EditorFor(model => model.Summary, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Summary, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar-o">
                            </i>
                        </div>
                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="dateRangePicker">

                <div class="form-group">
                    @Html.LabelFor(model => model.From, htmlAttributes: new {@class = "control-label col-md-2", @for = "dateFrom"})
                    <div class="col-md-10">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar-plus-o">
                                </i>
                            </div>
                            @Html.EditorFor(model => model.From, new {@Value = Model.From.ToString("dd/MM/yyyy HH:mm"), htmlAttributes = new {@class = "form-control", @id = "dateFrom", @placeholder = "dd/MM/yyyy HH:mm", @type = "text"}})
                            @Html.ValidationMessageFor(model => model.From, "", new {@class = "text-danger"})
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.To, htmlAttributes: new {@class = "control-label col-md-2", @for = "dateFrom"})
                    <div class="col-md-10">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar-plus-o">
                                </i>
                            </div>
                            @Html.EditorFor(model => model.To, new {@Value = Model.To.ToString("dd/MM/yyyy HH:mm"), htmlAttributes = new {@class = "form-control", @id = "dateTo", @placeholder = "dd/MM/yyyy HH:mm", @type = "text"}})
                            @Html.ValidationMessageFor(model => model.To, "", new {@class = "text-danger"})
                        </div>
                    </div>
                </div>
            </div>
            </div>

                <div class="list-group-item">
                    <div class="form-group">
                        @Html.LabelFor(model => model.IsAllDay, "All day event", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-1">
                            <div class="input-group">

                                @Html.CheckBoxFor(model => model.IsAllDay, htmlAttributes: new { @checked = "checked", @class = "checkbox" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.AlarmObj.Description, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar-o">
                                    </i>
                                </div>
                                @Html.TextAreaFor(model => model.AlarmObj.Description, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DurationObj, "Reminder time", htmlAttributes: new { @class = "control-label col-md-2", @for = "alarm" })
                        <div class="col-md-10">
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar-o">
                                    </i>
                                </div>
                                @Html.EditorFor(model => model.DurationObj, new { htmlAttributes = new { @class = "form-control", @id = "alarm"} })
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            @Html.HiddenFor(model => model.UID)
            <div class="form-group">
                <p> </p>
                <div class="col-md-offset-8 col-md-10">
                    <input type="button" value="Back" class="button" onclick="location.href = '@Url.Action("Index")'"/>
                    <input type="submit" value="Save" class="button"/>
                    <p></p>
                </div>
            
            </div>
     
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script type="text/javascript" src="~/scripts/moment-with-locales.min.js"></script>
<script type="text/javascript" src="~/scripts/bootstrap-datetimepicker.js"></script>
<script type="text/javascript" src="~/scripts/dateObject.js"></script>

iCalWebApp/Views/EventsList/Index.cshtml
@model IEnumerable<Core.Events.EventModel>

@{
    ViewBag.Title = "iCal Web App Events List";
    ViewBag.NoAlarm = "No alarm";
    Layout = "../Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p class="form-actions no-color">
    <input type="button" value="Create" class="button" onclick="location.href='@Url.Action("Create")'" />
</p>

@if (!Model.Any())
{
	<div class="alert alert-info">
		<strong>Info!</strong> Start adding events to see a list of them
	</div>
}
else
{
	<table class="table">
		<tr>
			<th>
				From
			</th>
			<th>
				To
			</th>
			<th>
				Name
			</th>
			<th>
				Commentary
			</th>
			<th>
				All day event
			</th>
			<th>
				Alarm time
			</th>
			<th>
				Alarm description
			</th>
			<th></th>
		</tr>

		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.From)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.To)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Summary)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Description)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.IsAllDay)
				</td>
				<td>
					@if (item.DurationObj == DateTime.MinValue)
					{
						@Html.ViewBag.NoAlarm
					}
					else
					{
						@Html.DisplayFor(modelItem => item.DurationObj)
					}
					
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.AlarmObj.Description)
				</td>

				<td>
					<input type="button" value="Edit" class="button-edit-delete" onclick="location.href = '@Url.Action("Edit", new { id = item.UID })'"/>
					<input type="button" value="Delete" class="button-edit-delete" onclick="location.href = '@Url.Action("Delete", new { id = item.UID })'"/>
				</td>
			</tr>
		}
		<tr>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td>Total items:</td>
			<td>@Model.Count()</td>
			<td>
				<input type="button" value="Delete all" class="button-edit-delete" onclick="location.href = '@Url.Action("DeleteAll")'"/>

			</td>
		</tr>

	</table>

    <input type="button" value="Download as calendar" class="button-edit-delete" onclick="location.href = '@Url.Action("DownloadCalendar")'"/>
    <p></p>
}
@using (Html.BeginForm("UploadCalendar", "EventsList", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

	<div class="modal-content modal-upload" style="display: none;">

		<div class="row col-md-offset-0">
			<input type="file" name="FileUpload1"/><br/>
			<input type="submit" name="Submit" id="Submit" class="button-edit-delete" value="Upload"/>
		</div>
	</div>

}
<p></p>
<input type="button" value="Upload Calendar" class="button-edit-delete" id="upload" onclick="toggleModal()"/>

<p></p>
<script type="text/javascript" src="~/scripts/uploadSlider.js"></script>

iCalWebApp/Views/Shared/DownloadModal.cshtml
@*<div class="modal-body">

    @using (Html.BeginForm("UploadCalendar", "EventsList", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {


        <div class="row">
            <input type="file" name="FileUpload1" /><br />
            <input type="submit" name="Submit" id="Submit" value="Upload" />
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal">
                    Cancel
                </button>
                <button type="submit" id="approve-btn"
                        class="btn btn-danger">
                    Save
                </button>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                $('#approve-btn').click(function () {
                    $('#modal-container').modal('hide');
                });
            });
        </script>
    }
    </div>*@

iCalWebApp/Views/Shared/UploadModal.cshtml
@*<div class="modal-body">

    @using (Html.BeginForm("UploadCalendar", "EventsList", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {


        <div class="row">
            <input type="file" name="FileUpload1" /><br />
            <input type="submit" name="Submit" id="Submit" value="Upload" />
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal">
                    Cancel
                </button>
                <button type="submit" id="approve-btn"
                        class="btn btn-danger">
                    Save
                </button>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                $('#approve-btn').click(function () {
                    $('#modal-container').modal('hide');
                });
            });
        </script>
    }
    </div>*@

iCalWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - iCalWebApp</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-2.2.1.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
</head>
<body class="body-content">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("iCalWebApp", "Index", "EventsList", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container content">
        @RenderBody()
    </div>

    <div class="navbar-inverse navbar-fixed-bottom">
        <footer class="text-center text-color">
            <p>&copy; @DateTime.Now.Year - iCalendar Web Application</p>
        </footer>
    </div>

</body>
</html>